### ISSUE TITLE
KeyError: u'void--unlabeled

### ISSUE THREAD

**Issue by amiltonwong** [mapillary/mapillary_vistas#1]
Hi, all,

I test the evaluation.py to get first impression. I use MVD validation labels as the predictions. All the process goes well except that I got "KeyError: u'void--unlabeled", [here](https://gist.github.com/amiltonwong/fdfc0b770fa875afe8baeadd46b39e20) is the details log.

Any suggestions?
THX!

**Comment by tobias-o** [comment]
Hi @amiltonwong 

Thanks for reporting the issue. It seems that you used the (8bit) label ground truth files.
I will fix the script to handle that case, but in meantime please try again and specify the (16bit) instance specific ground truth files with the `-g` switch.

Thanks

**Comment by tobias-o** [comment]
Should be fixed in `f1270a199ed2a534ba7eec1922132e1866ac0ba9`
