### ISSUE TITLE
Semantic segmentation

### ISSUE THREAD

**Issue by yong-qiang** [mapillary/mapillary_vistas#10]
I want to use the vistas dataset for semantic segmentation training, but the official provide labelids images with only instance segmentation, and no labelids images with semantic segmentation. What should I do?

**Comment by tobias-o** [comment]
the label ids are stored in the `labels` folder. You can check `demo.py` shipped with MVD on how to load them with python PIL

**Comment by yong-qiang** [comment]
Ok,thank you. 2207631278 邮箱：2207631278@qq.com 签名由 网易邮箱大师 定制 On 05/12/2020 21:36, Tobias Ollmann wrote: Closed #10. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
