### ISSUE TITLE
duplicated annotation ids in the validation dataset

### ISSUE THREAD

**Issue by garyfanhku** [mapillary/mapillary_vistas#11]
I found the annotation ids for bbox annotations in `validation/panoptic/panoptic_2018.json` seem to have duplicates. This will lead to issues when converting to coco instance format. Wonder if they are intentional and if there are specific reasons to keep it that way?

`len([item['id'] for item in segment_infos]), len(set([item['id'] for item in segment_infos]))
len([item['id'] for item in segment_infos]), len(set([item['id'] for item in segment_infos]))
(136031, 102954)`

Much appreciated!

**Comment by pkontschieder** [comment]
@garyfanhku The ID's are unique, but this is only required on a per-image basis, and not over the entire {training,validation,test} sets.
Please take a look at the label description [here](https://codalab.mapillary.com/competitions/42#learn_the_details), and you can see that an `annotation` exists on a per-image basis, holding its own `segments_info`. For this reason, we do not require IDs to be unique globally. HTH!
