### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by michaelowenliu** [mapillary/mapillary_vistas#14]
Hi, I requested access to the Mapillary Vistas Dataset ten days ago, but have yet received any relay. Is the dataset still available for the public?

**Comment by amwfarid** [comment]
I'm in the same situation. I sent them an email to ask for guidance, but received nothing yet.

Did you get any response from them?

**Comment by michaelowenliu** [comment]
> I'm in the same situation. I sent them an email to ask for guidance, but received nothing yet.
> 
> Did you get any response from them?

not yet.

**Comment by pkontschieder** [comment]
Hi @michaelowenliu and @amwfarid!
Apologies for not getting back on this earlier, however, we have just upgraded the dataset (see [this blog post](https://blog.mapillary.com/update/2021/01/18/vistas-2-dataset.html)), and made access easier through direct download. Just go to vistas.mapillary.com, fill out the request form again and you will immediately receive an email with download links and instructions how to unpack. HTH

**Comment by amwfarid** [comment]
@pkontschieder Thank you so much! I didn't realize there was an upgrade going on. I confirm that I got the download links.

Thank you so much for the hard efforts in making this dataset possible!
