### ISSUE TITLE
Error in Python 3

### ISSUE THREAD

**Issue by ternaus** [mapillary/mapillary_vistas#6]
```
python mapillary_vistas/tools/evaluation.py --help
Traceback (most recent call last):
  File "mapillary_vistas/tools/evaluation.py", line 127, in <module>
    import cProfile, pstats, StringIO
ModuleNotFoundError: No module named 'StringIO'

```

**Comment by tobias-o** [comment]
Hi @ternaus,

We are planning to support Python 3 in the future, but `mapillary_vistas` requires Python 2 for time being.

**Comment by ternaus** [comment]
Do you mind if I will create a pull request with a fix?

**Comment by tobias-o** [comment]
@ternaus I don't mind at all. Please go ahead :)
I'll leave this issue closed though, we can discuss further on the PR
