### ISSUE TITLE
Missing labels for pixels belonging to "Lanes"

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/mapillary_vistas#7]
It seems that there exist a large amount of pixels that belong to "Lane" are not labeled, could you explain why or whether is this my misunderstanding?

![image](https://user-images.githubusercontent.com/4639578/57603924-7715b900-7595-11e9-8af1-384c5a2b4c9a.png)

**Comment by tobias-o** [comment]
Hi @PkuRainBow !
Can you please paste the image key here so that I can have a look?

**Comment by PkuRainBow** [comment]
@tobias-o  Of course, the image ID is h-QX0W6qE0pw4c8JKEECpA

I mean there exist various Lines on the Road, how many categories of the Lines we define?

For example, "crosswalk-plain, bike-lane, service-line, marking/general. marking/crosswalk-zebra" all belong to the various Lines on the Road.

**Comment by tobias-o** [comment]
@PkuRainBow note that on the research edition, there are only two types of markings: `marking--general` and `marking--crosswalk-zebra`. Other related labels are `construction--flat--bike-lane`, `construction--flat--crosswalk-plain` and `construction--flat--service-lane` which you also mentioned.
If you need more fine grained labels, please contact our sales team (see [here](https://www.mapillary.com/dataset/vistas)) to purchase a commercial edition of MVD

Also have a look in `demo.py` on how to load the label files. They contain a color pallette to make them look nice when opened in image viewers. Some classes are mapped to the same color. The "real" image data is grayscale and its pixel values correspond to the index in the `labels` array in the config file.

**Comment by PkuRainBow** [comment]
@tobias-o Thanks for your reply, we mainly use the Mapillary datasets to improve the segmentation on the Cityscapes benchmark.
