### ISSUE TITLE
Labels for instance segmentation

### ISSUE THREAD

**Issue by ApoorvaSuresh** [mapillary/mapillary_vistas#8]
I find there are grayscale images for instance labels, but could you please tell me how to use them?

**Comment by tobias-o** [comment]
Please see the `demo.py` file how to handle instance files. It's part of the dataset

**Comment by ApoorvaSuresh** [comment]
Thank you for replying!

Instance labels are grayscale images?

**Comment by tobias-o** [comment]
Yes, instance labels are 16bit grayscale images :+1: 
8 bits encode class label (identical to the label image) and 8 bits encode the instance id.
