### ISSUE TITLE
Inconsistency in config.json file and in annotated images

### ISSUE THREAD

**Issue by mitalbert** [mapillary/mapillary_vistas#9]
I'm sorry I'm writing here this issue related to dataset files as I couldn't find a feedback form on the website.

The download file (v1.1) includes a file named config.json which includes all categories and information about them. One category named "object--vehicle--on-rails" is supposedly an object and should have instances however the json file says "instances": false on that category. Is this is typo or am I missing something?

I tried to find instances of that object and found [this annotation](https://www.mapillary.com/dataset/vistas?pKey=8SbwGx-2V0cP97r9AAaxzw&lat=52.02284283997872&lng=13.079901561083375&z=7.034908223928222&filter=%7B%22classarea%22:%5B%22object--vehicle--on-rails,0%22%5D,%22minors%22:%5B0%5D%7D) where rails are annotated as on-rails.
On the other hand, [this annotation](https://www.mapillary.com/dataset/vistas?pKey=ghZomxsm77VxDv02yPdRMg&lat=51.50315978478548&lng=12.701725505769446&z=5.900419814048325&filter=%7B%22classarea%22:%5B%22object--vehicle--on-rails,0%22%5D,%22minors%22:%5B0%5D%7D) seems to be correct.

**Comment by tobias-o** [comment]
Hi @mitalbert!

Thanks for reporting the wrong annotation, that's definitely an error.

Regarding the instance flag for on-rails we decided to not make it instance-specific because we do not separate between different wagons and we probably (hopefully) never observed two trains on the same rail (or also in adjacent ones). Hence, there is not enough data to properly learn instance-separation and we turned it off all along.

**Comment by mitalbert** [comment]
So if on-rails category is not instance specific anymore, this means that the information concerning objects in [blog post](https://research.mapillary.com/publication/iccv17a/) and in [this paper](https://research.mapillary.com/img/publications/ICCV17a.pdf) is not correct for the database v1.1. Are there any changes other than this and if so, is there a post about these changes?

**Comment by tobias-o** [comment]
on-rails was never instance specific (not in v1.0 and not in v1.1)

NB: not all `object` classes are `things` (i.e. instance specific)

**Comment by mitalbert** [comment]
> NB: not all object classes are things (i.e. instance specific)

Thanks, it's clear now.

> and we probably (hopefully) never observed two trains on the same rail (or also in adjacent ones)

Do you mean scenes like [this](https://www.mapillary.com/dataset/vistas?pKey=UHsNOR7M5i4lh3wiMEdvHg&lat=44.650778941706676&lng=8.676938108834179&z=3.2017839518784794&filter=%7B%22classarea%22:%5B%22object--vehicle--on-rails,0%22%5D%7D) or [this](https://www.mapillary.com/dataset/vistas?pKey=DX6nJZ-lB4o8OofJlb15PQ&lat=44.650778941706676&lng=8.676938108834179&z=3.2017839518784794&filter=%7B%22classarea%22:%5B%22object--vehicle--on-rails,0%22%5D%7D)?

**Comment by tobias-o** [comment]
Nice find :slightly_smiling_face: 
But the points still hold true. It's very rare and therefore we turned instance separation off.

**Comment by mitalbert** [comment]
I only looked at few images, didn't search for long frankly. I'm writing a script to combine datasets and will probably make instances out of on-rails in MVD  to make it compatible with other datasets. Thanks for making MVD publicly available.
